"""Regenerate caradonna_tung_hover_xfoil.yaml from the airfoiltools.com
XFOIL polar for NACA 0012 at Re=1M, Ncrit=5.

The Caradonna-Tung paper rotor (2-blade NACA 0012, R = 1.143 m,
1250 rpm) has chord Re ~= 1.4M at the 75% radial station -- close
enough to the 1M polar that we use it directly.

Run with:

    python _make_caradonna_tung_xfoil_yaml.py

Writes caradonna_tung_hover_xfoil.yaml in this directory.
"""
from __future__ import annotations

import csv
from pathlib import Path

HERE = Path(__file__).resolve().parent
CSV_PATH = HERE.parent.parent.parent / "Research" / "CaradonnaTung" / "naca0012_xfoil_re1M_ncrit5.csv"
OUT_YAML = HERE / "caradonna_tung_hover_xfoil.yaml"


def load_polar() -> list[tuple[float, float, float, float]]:
    """Read airfoiltools XFOIL CSV; skip header lines, return rows."""
    rows: list[tuple[float, float, float, float]] = []
    with CSV_PATH.open() as fh:
        for line in fh:
            parts = line.strip().split(",")
            if len(parts) < 5:
                continue
            try:
                alpha = float(parts[0])
                cl    = float(parts[1])
                cd    = float(parts[2])
                cm    = float(parts[4])
            except (ValueError, IndexError):
                continue
            rows.append((alpha, cl, cd, cm))
    return rows


def main() -> int:
    polar = load_polar()
    if not polar:
        raise RuntimeError(f"No numeric rows in {CSV_PATH}")
    # The XFOIL polar covers -19 to +19 deg. For BEM we need a few
    # post-stall anchors so the cl_max/cd table is well-defined far
    # outside the converged XFOIL window. Add Sheldahl-Klimas style
    # post-stall anchor points (flat-plate-like Cl, ~ +/-180 deg).
    extras = [
        (-180.0,  0.000, 0.0500, 0.000),
        (-160.0,  0.800, 0.4000, 0.000),
        (-90.0,   0.000, 1.8000, 0.000),
        (-30.0,  -1.000, 0.3000, 0.000),
        ( 30.0,   1.000, 0.3000, 0.000),
        ( 90.0,   0.000, 1.8000, 0.000),
        (160.0,  -0.800, 0.4000, 0.000),
        (180.0,   0.000, 0.0500, 0.000),
    ]
    # Merge by sorted alpha; XFOIL points dominate inside their range,
    # extras fill outside.
    merged = []
    alpha_min = polar[0][0]
    alpha_max = polar[-1][0]
    for row in extras:
        if row[0] < alpha_min or row[0] > alpha_max:
            merged.append(row)
    merged.extend(polar)
    merged.sort(key=lambda r: r[0])

    body = [
        "# Caradonna & Tung (1981) NASA TM-81232 hover rotor with a",
        "# tabulated NACA 0012 polar from airfoiltools.com XFOIL",
        "# (Re=1M, Ncrit=5).  Re at 75% radial station at 1250 rpm is",
        "# ~1.4M; the 1M polar is the closest available match.",
        "# Ncrit=5 chosen for closed-return wind-tunnel conditions",
        "# (matches the Castles-Gray rotor's polar choice).",
        "#",
        "# Generated by _make_caradonna_tung_xfoil_yaml.py from",
        "# Research/CaradonnaTung/naca0012_xfoil_re1M_ncrit5.csv",
        "# Post-stall (|alpha| > ~19 deg) extrapolated with",
        "# Sheldahl-Klimas-style flat-plate anchors so the table is",
        "# well-defined across all azimuths a rotor blade might visit.",
        "",
        "name: caradonna_tung_hover_xfoil",
        "",
        "rotor:",
        "  n_blades: 2",
        "  R_hub_m: 0.20",
        "  R_tip_m: 1.143",
        "",
        "air:",
        "  rho: 1.225",
        "  mu:  1.81206e-5",
        "  a:   340.0",
        "",
        "blade_stations:",
    ]
    for r in [0.221, 0.288, 0.355, 0.422, 0.489, 0.557, 0.624, 0.691,
              0.758, 0.825, 0.892, 0.959, 1.026, 1.093, 1.135]:
        body.append(f"  - {{r_m: {r:.3f}, chord_m: 0.1905, twist_deg: 0.0}}")
    body.extend([
        "",
        "airfoil_polar:",
        "  Re: 1.0e6",
        "  points:",
    ])
    for alpha, cl, cd, cm in merged:
        body.append(
            f"    - {{alpha_deg: {alpha:>7.3f}, cl: {cl:>+8.5f}, "
            f"cd: {cd:.5f}, cm: {cm:>+7.4f}}}"
        )
    body.extend([
        "",
        "operating_points:",
        "  - {U_wind_ms: 0.0, Omega_rpm: 1250.0, pitch_deg:  5.0}",
        "  - {U_wind_ms: 0.0, Omega_rpm: 1250.0, pitch_deg:  8.0}",
        "  - {U_wind_ms: 0.0, Omega_rpm: 1250.0, pitch_deg: 12.0}",
        "",
    ])
    OUT_YAML.write_text("\n".join(body))
    print(f"Wrote {OUT_YAML} ({len(merged)} polar rows)")
    _ = csv  # silence unused-import warning if csv module gets dropped
    return 0


if __name__ == "__main__":
    main()
