"""Compare dynbem.bem against CCBlade reference data for the Beaupoil
RAWES rotor.

CCBlade reference numbers come from the cached CSV at
verification/data/beaupoil_2026.csv, generated by the WISDEM-in-Docker
container under verification/ccblade_docker/.  See that directory's
README for how to rebuild the CSV when the rotor fixture or the
operating-point sweep changes.

For each (U_wind, Omega, pitch) point in the CSV we run dynbem.bem
with:

  - R_hub = identity (disk normal along +Z in NED -- same convention
    as helicopter hover; air-axis flow corresponds to v_climb)
  - wind_world = (0, 0, -U_wind)  -- wind flows UPWARD through the
    disk, putting the rotor in the autorotation / windmill regime
    that's the natural turbine analog of helicopter autorotation
  - collective_rad = pitch (Beaupoil sweep uses pitch=0, so the
    helicopter/turbine pitch-sign mismatch is moot)

Then we transform F_world / Q_spin back to non-dimensional CT and CQ.
**dynbem uses helicopter convention** (CT normalised by
`rho * pi R^2 * (Omega R)^2`), while CCBlade uses **wind-turbine
convention** (`rho * pi R^2 * U_wind^N`).  We convert CCBlade's
coefficients to helicopter convention for the comparison.

**Sign convention reconciliation.**  dynbem's `Q_spin` follows the
helicopter convention: positive when shaft drives the rotor, negative
when the rotor extracts power from the air (autorotation / windmill).
CCBlade's `Q` follows the wind-turbine convention: positive when the
rotor extracts torque.  Both BEMs therefore *agree on the physical
situation* (the Beaupoil rotor at V_wind=10 m/s, Omega=192.4 rpm,
pitch=0 is in autorotation -- wind drives the rotor), but they
disagree on the SIGN of Q.  This module negates dynbem's CQ_db before
comparing, so a positive value in either column means "rotor extracts
torque from wind".

After Brent's-method-on-phi (Ning 2014) was added to the windmill
solver, the original 2025 disagreement (dynbem T ~1.4x CCBlade,
|Q| ~3.6x) collapsed: the old fixed-point iteration was locking
into the stalled basin of attraction on the cambered SG6040 at
zero pitch, not a real model mismatch.  Current state across the
25 operating points (V_wind 5..16 m/s, Omega 100..300 rpm):

    CT err: median 1.4 %, mean 1.4 %, RMSE 1.4 %, max 1.8 %
    CQ err: median 2.7 %, mean 3.3 %, RMSE 3.7 %, max 11.1 %

The 11.1 % CQ max is at the autorotation crossing (V=5, Omega=192.4)
where |CQ_cc| = 2e-5: absolute disagreement is negligible (~2e-6),
relative error inflates because of the near-zero denominator.
"""
from __future__ import annotations

import argparse
import csv
import math
import sys
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np


def _sample_evenly(items: list, n: int | None) -> list:
    if n is None or n <= 0 or n >= len(items):
        return items
    idx = np.linspace(0, len(items) - 1, n).round().astype(int)
    seen: set[int] = set()
    out = []
    for i in idx:
        i = int(i)
        if i not in seen:
            seen.add(i)
            out.append(items[i])
    return out


ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from dynbem.bem import BEMModel
from dynbem import RotorInputs, create_aero
from dynbem.rotor_definition import load as load_rotor
from dynbem.rotor_state import QuasiStaticRotorState

ROTOR_YAML = ROOT / "rotors" / "beaupoil_2026" / "rotor.yaml"
CCBLADE_CSV = ROOT / "verification" / "data" / "beaupoil_2026.csv"
RHO = 1.225


@dataclass
class Comparison:
    U_wind_ms: float
    Omega_rpm: float
    pitch_deg: float
    # CCBlade reference (helicopter-convention coefficients):
    CT_cc: float
    CQ_cc: float
    T_cc_N: float
    Q_cc_Nm: float
    # dynbem prediction:
    CT_db: float
    CQ_db: float
    T_db_N: float
    Q_db_Nm: float

    @property
    def ct_err(self) -> float:
        if abs(self.CT_cc) < 1e-6:
            return float("inf")
        return abs(self.CT_db - self.CT_cc) / abs(self.CT_cc)

    @property
    def cq_err(self) -> float:
        if abs(self.CQ_cc) < 1e-6:
            return float("inf")
        return abs(self.CQ_db - self.CQ_cc) / abs(self.CQ_cc)


@dataclass
class Survey:
    comparisons: list[Comparison] = field(default_factory=list)
    sample: int | None = None

    def ct_errors(self) -> np.ndarray:
        return np.array([c.ct_err for c in self.comparisons
                         if math.isfinite(c.ct_err)])

    def cq_errors(self) -> np.ndarray:
        return np.array([c.cq_err for c in self.comparisons
                         if math.isfinite(c.cq_err)])


def load_ccblade_csv(path: Path) -> list[dict]:
    rows: list[dict] = []
    with path.open(encoding="ascii", newline="") as f:
        reader = csv.DictReader(f)
        for row in reader:
            rows.append({k: float(v) for k, v in row.items()})
    return rows


def cc_to_heli_coeffs(row: dict, rho: float, R: float) -> tuple[float, float]:
    """Convert CCBlade CT/CQ (turbine convention, normalised by U_wind)
    to helicopter convention (normalised by Omega*R)."""
    omega = row["Omega_rpm"] * math.pi / 30.0
    A = math.pi * R**2
    CT_heli = row["T_N"] / (rho * A * (omega * R)**2)
    CQ_heli = row["Q_Nm"] / (rho * A * (omega * R)**2 * R)
    return CT_heli, CQ_heli


def dynbem_at_point(model: BEMModel, U_wind_ms: float, Omega_rpm: float,
                    pitch_deg: float, rho: float
                    ) -> tuple[float, float, float, float]:
    """Run dynbem at one wind-turbine-style operating point.

    Returns ``(CT, CQ, T_N, Q_spin_Nm)`` -- both coefficients in
    helicopter normalisation."""
    R = model.defn.blade.radius_m
    omega = Omega_rpm * math.pi / 30.0
    A = math.pi * R**2
    # NED: rotor disk plane is XY, hub axis is +Z (down). Wind blowing
    # up through the disk == autorotation/windmill: wind_world[2] < 0.
    inp = RotorInputs(
        collective_rad=math.radians(pitch_deg),
        tilt_lon=0.0, tilt_lat=0.0,
        R_hub=np.eye(3),
        v_hub_world=np.zeros(3),
        wind_world=np.array([0.0, 0.0, -U_wind_ms]),
        t=0.0,
        rho_kg_m3=RHO,
        omega_rad_s=omega,
    )
    state = QuasiStaticRotorState()
    result, _ = model.compute_forces(inp, state)
    T = -result.F_world[2]
    CT = T / (rho * A * (omega * R)**2)
    CQ = result.Q_spin / (rho * A * (omega * R)**2 * R)
    return CT, CQ, T, result.Q_spin


def run_survey(sample: int | None = None) -> Survey:
    """Sweep the CCBlade CSV (or a sampled subset) and compare dynbem.

    sample=None -> every row in the CSV.  sample=N -> N evenly-spaced.
    """
    if not CCBLADE_CSV.exists():
        return Survey(sample=sample)
    if not ROTOR_YAML.exists():
        return Survey(sample=sample)

    model = create_aero(load_rotor(str(ROTOR_YAML)), "bem")
    R = model.defn.blade.radius_m
    rows = _sample_evenly(load_ccblade_csv(CCBLADE_CSV), sample)

    survey = Survey(sample=sample)
    for row in rows:
        CT_cc, CQ_cc = cc_to_heli_coeffs(row, RHO, R)
        CT_db, CQ_db, T_db, Q_db = dynbem_at_point(
            model, row["U_wind_ms"], row["Omega_rpm"], row["pitch_deg"], RHO)
        # Flip dynbem CQ + Q sign to match the wind-turbine convention
        # used by CCBlade.  See the module docstring for the convention
        # discussion -- both BEMs agree physically; signs are just
        # opposite.
        survey.comparisons.append(Comparison(
            U_wind_ms=row["U_wind_ms"], Omega_rpm=row["Omega_rpm"],
            pitch_deg=row["pitch_deg"],
            CT_cc=CT_cc, CQ_cc=CQ_cc, T_cc_N=row["T_N"], Q_cc_Nm=row["Q_Nm"],
            CT_db=CT_db, CQ_db=-CQ_db, T_db_N=T_db, Q_db_Nm=-Q_db,
        ))
    return survey


def _print_survey(survey: Survey) -> None:
    if not survey.comparisons:
        print("survey empty -- missing rotor.yaml or beaupoil_2026.csv?")
        return
    print(f"{'U':>5}  {'rpm':>6}  {'pitch':>5}   "
          f"{'CT_cc':>7}  {'CT_db':>7}  {'CT err':>7}   "
          f"{'CQ_cc':>8}  {'CQ_db':>8}  {'CQ err':>7}")
    for c in survey.comparisons:
        print(f"{c.U_wind_ms:5.1f}  {c.Omega_rpm:6.1f}  {c.pitch_deg:5.1f}   "
              f"{c.CT_cc:7.4f}  {c.CT_db:7.4f}  {c.ct_err:6.1%}   "
              f"{c.CQ_cc:+8.5f}  {c.CQ_db:+8.5f}  {c.cq_err:6.1%}")
    ct = survey.ct_errors()
    cq = survey.cq_errors()
    print()
    print(f"CT err: n={len(ct)} median={np.median(ct):.1%} mean={ct.mean():.1%} "
          f"RMSE={np.sqrt((ct**2).mean()):.1%} max={ct.max():.1%}")
    print(f"CQ err: n={len(cq)} median={np.median(cq):.1%} mean={cq.mean():.1%} "
          f"RMSE={np.sqrt((cq**2).mean()):.1%} max={cq.max():.1%}")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    p.add_argument("--sample", type=int, default=None, metavar="N",
                   help="evenly-sample N rows from the CCBlade CSV (smoke test); "
                        "omit to compare every row")
    args = p.parse_args()
    if args.sample is not None:
        print(f"** SAMPLED MODE: {args.sample} of available rows\n")
    _print_survey(run_survey(sample=args.sample))
    return 0


if __name__ == "__main__":
    sys.exit(main())
