"""Compare dynbem.bem against CCBlade reference data on NREL Phase VI.

NREL Unsteady Aerodynamics Experiment Phase VI (UAE) Sequence S:
2-blade twisted/tapered horizontal-axis wind turbine, S809 airfoil,
R = 5.029 m, fixed 72 RPM, tip pitch +3 deg (pitch-to-feather).
Tested in the NASA Ames 80 ft x 120 ft tunnel, May 2000.

This is the "right" CCBlade cross-check (vs the earlier Beaupoil
cross-check which was mismatched-by-design): Phase VI is a real
wind turbine in the operating envelope CCBlade was calibrated for,
and now that dynbem.BladeGeometry supports r_stations_m /
chord_stations_m / twist_stations_deg both BEMs see the same
twisted/tapered geometry.

CCBlade reference numbers come from the cached CSV at
verification/data/nrel_phase_vi_seqS.csv, generated by the
WISDEM-in-Docker container under verification/ccblade_docker/.

Convention reconciliation (same as the Beaupoil verifier):
  - dynbem positive collective is pitch-to-stall (helicopter), CCBlade
    positive pitch is pitch-to-feather (turbine).  -> negate pitch
    when handing off to dynbem.
  - Twist values transfer 1:1 (both BEMs interpret positive twist as
    pitch-to-stall direction at that station).
  - Wind blowing axially into the disk: wind_world = (0, 0, -U_wind)
    in NED (wind flowing up through the disk, autorotation/windmill
    regime in dynbem terminology).
  - dynbem CQ < 0 when wind drives the rotor; CCBlade CQ > 0 in the
    same situation.  Negate dynbem CQ for comparison.
"""
from __future__ import annotations

import argparse
import csv
import math
import sys
from dataclasses import dataclass, field
from pathlib import Path

import numpy as np


def _sample_evenly(items: list, n: int | None) -> list:
    if n is None or n <= 0 or n >= len(items):
        return items
    idx = np.linspace(0, len(items) - 1, n).round().astype(int)
    seen: set[int] = set()
    out = []
    for i in idx:
        i = int(i)
        if i not in seen:
            seen.add(i)
            out.append(items[i])
    return out


ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from dynbem.bem import BEMModel
from dynbem import RotorInputs
from dynbem.rotor_definition import load as load_rotor
from dynbem.rotor_state import QuasiStaticRotorState

ROTOR_YAML = ROOT / "rotors" / "nrel_phase_vi" / "rotor.yaml"
CCBLADE_CSV = ROOT / "verification" / "data" / "nrel_phase_vi_seqS.csv"
RHO = 1.225


@dataclass
class Comparison:
    U_wind_ms: float
    Omega_rpm: float
    pitch_deg: float
    # CCBlade reference, normalised in helicopter convention for the
    # comparison (T / (rho * pi R^2 * (Omega R)^2)):
    CT_cc: float
    CQ_cc: float
    T_cc_N: float
    Q_cc_Nm: float
    # dynbem prediction (after Q-sign flip to match turbine convention):
    CT_db: float
    CQ_db: float
    T_db_N: float
    Q_db_Nm: float

    @property
    def ct_err(self) -> float:
        if abs(self.CT_cc) < 1e-6:
            return float("inf")
        return abs(self.CT_db - self.CT_cc) / abs(self.CT_cc)

    @property
    def cq_err(self) -> float:
        if abs(self.CQ_cc) < 1e-6:
            return float("inf")
        return abs(self.CQ_db - self.CQ_cc) / abs(self.CQ_cc)


@dataclass
class Survey:
    comparisons: list[Comparison] = field(default_factory=list)
    sample: int | None = None

    def ct_errors(self) -> np.ndarray:
        return np.array([c.ct_err for c in self.comparisons
                         if math.isfinite(c.ct_err)])

    def cq_errors(self) -> np.ndarray:
        return np.array([c.cq_err for c in self.comparisons
                         if math.isfinite(c.cq_err)])


def load_ccblade_csv(path: Path) -> list[dict]:
    with path.open(encoding="ascii", newline="") as f:
        return [{k: float(v) for k, v in row.items()}
                for row in csv.DictReader(f)]


def cc_to_heli_coeffs(row: dict, rho: float, R: float) -> tuple[float, float]:
    """Re-normalise CCBlade's T/Q to helicopter convention so they are
    directly comparable to dynbem (which normalises by Omega*R)."""
    omega = row["Omega_rpm"] * math.pi / 30.0
    A = math.pi * R**2
    CT_heli = row["T_N"] / (rho * A * (omega * R)**2)
    CQ_heli = row["Q_Nm"] / (rho * A * (omega * R)**2 * R)
    return CT_heli, CQ_heli


def dynbem_at_point(model: BEMModel, U_wind_ms: float, Omega_rpm: float,
                    cc_pitch_deg: float, rho: float
                    ) -> tuple[float, float, float, float]:
    """Run dynbem at one CCBlade operating point.  cc_pitch_deg uses the
    CCBlade convention (positive = pitch-to-feather); we negate it
    before handing off because dynbem treats positive collective as
    pitch-to-stall."""
    R = model.defn.blade.radius_m
    omega = Omega_rpm * math.pi / 30.0
    A = math.pi * R**2
    inp = RotorInputs(
        collective_rad=math.radians(-cc_pitch_deg),  # SIGN FLIP
        tilt_lon=0.0, tilt_lat=0.0,
        R_hub=np.eye(3),
        v_hub_world=np.zeros(3),
        wind_world=np.array([0.0, 0.0, -U_wind_ms]),
        t=0.0,
    )
    state = QuasiStaticRotorState(omega_rad_s=omega)
    result, _ = model.compute_forces(inp, state)
    T = -result.F_world[2]
    CT = T / (rho * A * (omega * R)**2)
    CQ = result.Q_spin / (rho * A * (omega * R)**2 * R)
    return CT, CQ, T, result.Q_spin


def run_survey(sample: int | None = None) -> Survey:
    if not CCBLADE_CSV.exists() or not ROTOR_YAML.exists():
        return Survey(sample=sample)
    model = BEMModel(defn=load_rotor(str(ROTOR_YAML)))
    R = model.defn.blade.radius_m
    rows = _sample_evenly(load_ccblade_csv(CCBLADE_CSV), sample)

    survey = Survey(sample=sample)
    for row in rows:
        CT_cc, CQ_cc = cc_to_heli_coeffs(row, RHO, R)
        CT_db, CQ_db, T_db, Q_db = dynbem_at_point(
            model, row["U_wind_ms"], row["Omega_rpm"], row["pitch_deg"], RHO)
        survey.comparisons.append(Comparison(
            U_wind_ms=row["U_wind_ms"], Omega_rpm=row["Omega_rpm"],
            pitch_deg=row["pitch_deg"],
            CT_cc=CT_cc, CQ_cc=CQ_cc, T_cc_N=row["T_N"], Q_cc_Nm=row["Q_Nm"],
            # dynbem CQ flipped to match CCBlade's turbine-extraction sign
            CT_db=CT_db, CQ_db=-CQ_db, T_db_N=T_db, Q_db_Nm=-Q_db,
        ))
    return survey


def _print_survey(survey: Survey) -> None:
    if not survey.comparisons:
        print("survey empty -- missing fixture or CCBlade CSV?")
        return
    print(f"{'U':>5}  {'rpm':>5}  {'pitch':>5}   "
          f"{'CT_cc':>7}  {'CT_db':>7}  {'CT err':>7}   "
          f"{'CQ_cc':>8}  {'CQ_db':>8}  {'CQ err':>7}")
    for c in survey.comparisons:
        print(f"{c.U_wind_ms:5.1f}  {c.Omega_rpm:5.1f}  {c.pitch_deg:5.1f}   "
              f"{c.CT_cc:7.4f}  {c.CT_db:7.4f}  {c.ct_err:6.1%}   "
              f"{c.CQ_cc:+8.5f}  {c.CQ_db:+8.5f}  {c.cq_err:6.1%}")
    ct = survey.ct_errors()
    cq = survey.cq_errors()
    print()
    print(f"CT err: n={len(ct)} median={np.median(ct):.1%} mean={ct.mean():.1%} "
          f"RMSE={np.sqrt((ct**2).mean()):.1%} max={ct.max():.1%}")
    print(f"CQ err: n={len(cq)} median={np.median(cq):.1%} mean={cq.mean():.1%} "
          f"RMSE={np.sqrt((cq**2).mean()):.1%} max={cq.max():.1%}")


def main() -> int:
    p = argparse.ArgumentParser(description=__doc__.splitlines()[0] if __doc__ else "")
    p.add_argument("--sample", type=int, default=None, metavar="N",
                   help="evenly-sample N of the available rows; "
                        "omit to compare every row")
    args = p.parse_args()
    if args.sample is not None:
        print(f"** SAMPLED MODE: {args.sample} rows\n")
    _print_survey(run_survey(sample=args.sample))
    return 0


if __name__ == "__main__":
    sys.exit(main())
