"""One-shot helper: emit inputs/beaupoil_2026.yaml from local sources.

Geometry comes from rotors/beaupoil_2026/rotor.yaml; the polar is the
SG6040 XFOIL file next to it. Re-run when either source changes.

Operating-point sweep: at the measured autorotation hover point
(V_wind = 10 m/s, Omega = 192.4 rpm = 20.148 rad/s) plus a 2-D grid
around it so we can compare CT/CQ curves against dynbem.
"""
from __future__ import annotations

import csv
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent.parent
ROTOR_DIR = REPO_ROOT / "rotors" / "beaupoil_2026"
POLAR_CSV = ROTOR_DIR / "sg6040_re500k.csv"

# Beaupoil RAWES rotor (rotor.yaml):
#   4 blades, R = 2.5 m, root cutout = 0.5 m, chord = 0.20 m (constant),
#   twist = 0 deg, SG6040 airfoil.
# CCBlade integrates radially between Rhub and Rtip; for a constant-chord
# untwisted blade just a handful of stations are enough.
R_HUB_M = 0.5
R_TIP_M = 2.5
CHORD_M = 0.20
TWIST_DEG = 0.0
N_STATIONS = 11

BLADE_STATIONS = [
    (round(R_HUB_M + (R_TIP_M - R_HUB_M) * i / (N_STATIONS - 1), 4),
     CHORD_M, TWIST_DEG)
    for i in range(N_STATIONS)
]

ROTOR = dict(
    n_blades=4,
    R_hub_m=R_HUB_M,
    R_tip_m=R_TIP_M,
    precone_deg=0.0,
    tilt_deg=0.0,
)

# Measured autorotation equilibrium per rotor.yaml:
#   V_wind = 10 m/s, Omega = 20.148 rad/s = 192.4 rpm.
# Sweep wind speed and RPM around that to compare CT/CQ curves.
WIND_MS    = [5.0, 7.0, 10.0, 13.0, 16.0]
OMEGA_RPMS = [100.0, 150.0, 192.4, 250.0, 300.0]
PITCH_DEG  = 0.0

OPERATING_POINTS = [
    dict(U_wind_ms=U, Omega_rpm=W, pitch_deg=PITCH_DEG)
    for U in WIND_MS for W in OMEGA_RPMS
]


def read_polar(path: Path) -> list[tuple[float, float, float]]:
    points: list[tuple[float, float, float]] = []
    with path.open(encoding="ascii", newline="") as f:
        reader = csv.reader(f)
        for row in reader:
            if row and row[0].strip() == "Alpha":
                break
        for row in reader:
            if not row or not row[0].strip():
                continue
            try:
                alpha, cl, cd = float(row[0]), float(row[1]), float(row[2])
            except ValueError:
                continue
            points.append((alpha, cl, cd))
    if not points:
        raise SystemExit(f"no polar points read from {path}")
    return points


def emit_yaml(out_path: Path) -> None:
    polar = read_polar(POLAR_CSV)
    lines: list[str] = []
    lines.append("# Auto-generated by inputs/_make_beaupoil_2026_yaml.py.")
    lines.append("# Source: rotors/beaupoil_2026/rotor.yaml + sg6040_re500k.csv.")
    lines.append('name: beaupoil_2026')
    lines.append("rotor:")
    for k, v in ROTOR.items():
        lines.append(f"  {k}: {v}")
    lines.append("air:")
    lines.append("  rho: 1.225")
    lines.append("  mu: 1.81206e-5")
    lines.append("blade_stations:")
    for r_m, chord_m, twist_deg in BLADE_STATIONS:
        lines.append(f"  - {{r_m: {r_m:.4f}, chord_m: {chord_m:.3f}, twist_deg: {twist_deg:.2f}}}")
    lines.append("airfoil_polar:")
    lines.append("  Re: 500000.0")
    lines.append("  points:")
    for alpha, cl, cd in polar:
        lines.append(f"    - {{alpha_deg: {alpha:.2f}, cl: {cl:.4f}, cd: {cd:.5f}}}")
    lines.append("operating_points:")
    for op in OPERATING_POINTS:
        lines.append(
            f"  - {{U_wind_ms: {op['U_wind_ms']:.1f}, "
            f"Omega_rpm: {op['Omega_rpm']:.1f}, "
            f"pitch_deg: {op['pitch_deg']:.1f}}}"
        )
    out_path.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"wrote {out_path} ({len(lines)} lines, {len(OPERATING_POINTS)} operating points)")


if __name__ == "__main__":
    emit_yaml(HERE / "beaupoil_2026.yaml")
