"""One-shot helper: emit inputs/nrel_phase_vi.yaml from local sources.

Re-run when the chord/twist table or polar source changes. Output
is committed alongside this script so the Docker run is hermetic
(no network, no host-Python).

Sources:
  - chord/twist : Hand et al. (2001) NREL/TP-500-29955 Table A-1
                  (TP-500-29955/source.pdf p64 in the Research dir).
                  Sequence S, twisted-tapered blade, 2 blades.
                  Values below are the airfoil section (S809) only;
                  the inner root cylinder is omitted because CCBlade
                  starts at R_hub.
  - polar       : rotors/nrel_phase_vi/xf-s809-nr-1000000.csv
                  (XFOIL S809 at Re=1e6, NCrit=9).
"""
from __future__ import annotations

import csv
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parent.parent.parent
POLAR_CSV = REPO_ROOT / "rotors" / "nrel_phase_vi" / "xf-s809-nr-1000000.csv"

# Hand 2001 Table A-1, airfoil section only (S809 starts at ~1.26 m).
# These are the published Sequence S geometry rows; refine from the PDF
# if you spot drift vs the source.
BLADE_STATIONS_M_M_DEG = [
    # (r_m,  chord_m, twist_deg)
    (1.257, 0.737, 22.00),
    (1.343, 0.728, 18.30),
    (1.510, 0.711, 14.29),
    (1.648, 0.697, 11.91),
    (1.952, 0.666,  8.42),
    (2.257, 0.636,  6.16),
    (2.343, 0.627,  5.66),
    (2.562, 0.605,  4.66),
    (2.867, 0.574,  3.42),
    (3.172, 0.543,  2.49),
    (3.476, 0.512,  1.83),
    (3.781, 0.482,  1.40),
    (4.086, 0.451,  1.13),
    (4.391, 0.420,  0.96),
    (4.696, 0.389,  0.85),
    (5.000, 0.358,  0.79),
]

ROTOR = dict(
    n_blades=2,
    R_hub_m=1.257,   # start of airfoil; matches first station above
    R_tip_m=5.029,   # 10.058 m diameter / 2
    precone_deg=0.0,
    tilt_deg=0.0,
)

# Operating points: NREL Sequence S, fixed-pitch stall-regulated.
# 72 RPM, pitch +3 deg, wind speed 5..25 m/s (1 m/s steps).
OPERATING_POINTS = [
    dict(U_wind_ms=float(U), Omega_rpm=72.0, pitch_deg=3.0)
    for U in range(5, 26)
]


def read_polar(path: Path) -> list[tuple[float, float, float]]:
    points: list[tuple[float, float, float]] = []
    with path.open(encoding="ascii", newline="") as f:
        reader = csv.reader(f)
        # skip XFOIL header until we see the column row.
        for row in reader:
            if row and row[0].strip() == "Alpha":
                break
        for row in reader:
            if not row or not row[0].strip():
                continue
            try:
                alpha, cl, cd = float(row[0]), float(row[1]), float(row[2])
            except ValueError:
                continue
            points.append((alpha, cl, cd))
    if not points:
        raise SystemExit(f"no polar points read from {path}")
    return points


def emit_yaml(out_path: Path) -> None:
    polar = read_polar(POLAR_CSV)
    lines: list[str] = []
    lines.append("# Auto-generated by inputs/_make_nrel_phase_vi_yaml.py.")
    lines.append("# Source: Hand 2001 (NREL/TP-500-29955) Table A-1 + S809 XFOIL polar.")
    lines.append('name: nrel_phase_vi_seqS')
    lines.append("rotor:")
    for k, v in ROTOR.items():
        lines.append(f"  {k}: {v}")
    lines.append("air:")
    lines.append("  rho: 1.225")
    lines.append("  mu: 1.81206e-5")
    lines.append("blade_stations:")
    for r_m, chord_m, twist_deg in BLADE_STATIONS_M_M_DEG:
        lines.append(f"  - {{r_m: {r_m:.3f}, chord_m: {chord_m:.3f}, twist_deg: {twist_deg:.2f}}}")
    lines.append("airfoil_polar:")
    lines.append("  Re: 1.0e6")
    lines.append("  points:")
    for alpha, cl, cd in polar:
        lines.append(f"    - {{alpha_deg: {alpha:.2f}, cl: {cl:.4f}, cd: {cd:.5f}}}")
    lines.append("operating_points:")
    for op in OPERATING_POINTS:
        lines.append(
            f"  - {{U_wind_ms: {op['U_wind_ms']:.1f}, "
            f"Omega_rpm: {op['Omega_rpm']:.1f}, "
            f"pitch_deg: {op['pitch_deg']:.1f}}}"
        )
    out_path.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"wrote {out_path} ({len(lines)} lines)")


if __name__ == "__main__":
    emit_yaml(HERE / "nrel_phase_vi.yaml")
