"""Drive OpenFAST AeroDyn standalone for a rotor described by a YAML.

The YAML schema mirrors verification/ccblade_docker/inputs/*.yaml as
closely as possible -- same rotor + polar + operating-point shape --
plus a `wake` section that controls AeroDyn's DBEMT / skew options.

For each operating point we:

  1. Write an aerodyn_driver .dvr file, an AeroDyn15 .dat file, a
     blade .dat file, and an airfoil .dat file under /tmp/<case>/.
  2. Invoke /openfast/install/bin/aerodyn_driver against the .dvr.
  3. Parse the resulting .out ASCII file, average the last full rotor
     revolution, and record (T, Q, P, CT, CP) into a per-rotor CSV.

The settling-then-average approach matches how dynbem.envelope drives
the dynamic-inflow models: spin up at fixed inputs until lambda
relaxes to steady state, then read off the converged values.

YAML schema:

    name: <free-form, used to name the output CSV>
    rotor:
      n_blades: int
      R_hub_m: float          # blade inboard cutout
      R_tip_m: float
      precone_deg: float      # optional, defaults 0
    air:
      rho: float              # optional, defaults 1.225
      mu: float               # optional, defaults 1.81206e-5
      a:   float              # speed of sound; optional, defaults 335
    blade_stations:
      - {r_m: float, chord_m: float, twist_deg: float}
      - ...                   # sorted by r_m; r_m is from rotor centre
    airfoil_polar:
      Re: float
      points:
        - {alpha_deg: float, cl: float, cd: float}
        - ...                 # cm column gets cm=0 added by the writer
    wake:
      WakeMod: 2              # 1=BEMT, 2=DBEMT, 3=OLAF; default 2
      DBEMT_Mod: 1            # 1=const tau1 (matches dynbem.oye Mod=1)
      tau1_const: 10.0        # s; only used for DBEMT_Mod=1
      SkewMod: 1              # 1=uncoupled, 2=Pitt-Peters; default 1
      TipLoss: true
      HubLoss: true
    operating_points:
      - {U_wind_ms: float, Omega_rpm: float, pitch_deg: float,
         settle_s: float}     # time to run before averaging
      - ...
"""
from __future__ import annotations

import argparse
import csv
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

import numpy as np
import yaml


AD_DRIVER = "/openfast/install/bin/aerodyn_driver"


# ---------------------------------------------------------------------------
# Input-file writers
# ---------------------------------------------------------------------------


def write_airfoil(path: Path, polar: dict) -> None:
    """Write a single AeroDyn15 airfoil .dat file (steady polar).

    The minimum-viable airfoil file: header + InterpOrd/NumCoords/etc.
    metadata + a single Re table with Alpha, Cl, Cd, Cm columns.
    """
    pts = polar["points"]
    re = polar.get("Re", 1.0e6)
    lines = [
        "! Airfoil polar generated by verification/openfast_docker/run.py",
        "! ------------------------------------------------------------------",
        '"DEFAULT"   InterpOrd        ! interpolation order',
        "1           NonDimArea       ! area for tabulated parameters",
        "0           NumCoords        ! number of points for blade shape",
        '"unused"    BL_file          ! boundary-layer file',
        "1           NumTabs          ! number of airfoil tables",
        "! ============== data for table 1 ==============",
        f"{re}      Re               ! Reynolds number",
        "0           UserProp         ! user-defined property",
        "False       InclUAdata       ! include unsteady-aero parameters",
        "! ----- polar -----",
        f"{len(pts)}   NumAlf          ! number of (alpha, Cl, Cd, Cm) rows",
        "!   Alpha       Cl          Cd          Cm",
        "!   (deg)       (-)         (-)         (-)",
    ]
    for p in pts:
        lines.append(
            f"   {p['alpha_deg']:>9.3f}   {p['cl']:>9.5f}   {p['cd']:>9.5f}   0.00000"
        )
    path.write_text("\n".join(lines) + "\n")


def write_blade(path: Path, stations: list[dict], af_id: int = 1) -> None:
    """Write an AeroDyn15 blade .dat file.

    BlSpn is the spanwise coordinate (m from blade root). dynbem and the
    YAML use r_m from rotor centre, so we subtract R_hub before writing.
    """
    rmin = min(s["r_m"] for s in stations)
    lines = [
        "------- AERODYN BLADE INPUT FILE -----------------------------------",
        "Generated by verification/openfast_docker/run.py",
        "======  Blade Properties ============================================",
        f"{len(stations)}                   NumBlNds   - Number of blade nodes",
        "    BlSpn        BlCrvAC      BlSwpAC      BlCrvAng     BlTwist       BlChord      BlAFID",
        "     (m)          (m)          (m)          (deg)         (deg)         (m)          (-)",
    ]
    for s in sorted(stations, key=lambda s: s["r_m"]):
        span = s["r_m"] - rmin
        lines.append(
            f"   {span:>9.5f}   {0.0:>9.5f}   {0.0:>9.5f}   {0.0:>9.5f}   "
            f"{s['twist_deg']:>9.5f}   {s['chord_m']:>9.5f}   {af_id:>4d}"
        )
    path.write_text("\n".join(lines) + "\n")


def write_aerodyn_primary(
    path: Path, wake: dict, air: dict, airfoil_rel: str, blade_rel: str,
    dt_s: float,
) -> None:
    """Write the AeroDyn15 primary input .dat file."""
    rho   = air.get("rho", 1.225)
    mu    = air.get("mu", 1.81206e-5)
    csnd  = air.get("a", 335.0)
    wake_mod  = int(wake.get("WakeMod", 2))
    dbemt_mod = int(wake.get("DBEMT_Mod", 1))
    tau1      = float(wake.get("tau1_const", 10.0))
    skew_mod  = int(wake.get("SkewMod", 1))
    tip_loss  = ".TRUE." if wake.get("TipLoss", True) else ".FALSE."
    hub_loss  = ".TRUE." if wake.get("HubLoss", True) else ".FALSE."

    # AeroDyn always reads ADBlFile(1), ADBlFile(2), ADBlFile(3) regardless
    # of NumBlades; the trailing entries are unused when NumBl < 3. Always
    # emit three; reuse the same blade file (rotors with mixed blade designs
    # aren't supported here).
    blade_lines = "\n".join(
        f'"{blade_rel}"          ADBlFile({i+1})' for i in range(3)
    )

    body = f"""------- AERODYN v15.03.* INPUT FILE ------------------------------------------------
Generated by verification/openfast_docker/run.py
======  General Options  ============================================================================
False       Echo
{dt_s}      DTAero
{wake_mod}        WakeMod
1           AFAeroMod
0           TwrPotent
0           TwrShadow
False       TwrAero
False       FrozenWake
False       CavitCheck
False       Buoyancy
False       CompAA
"unused"    AA_InputFile
======  Environmental Conditions  ===================================================================
{rho}       AirDens
{mu}        KinVisc
{csnd}      SpdSound
103500.0    Patm
1700.0      Pvap
======  Blade-Element/Momentum Theory Options  ======================================================
{skew_mod}        SkewMod
"default"   SkewModFactor
{tip_loss}  TipLoss
{hub_loss}  HubLoss
True        TanInd
True        AIDrag
True        TIDrag
"Default"   IndToler
500         MaxIter
======  Dynamic Blade-Element/Momentum Theory Options  ==============================================
{dbemt_mod}        DBEMT_Mod
{tau1}      tau1_const
======  OLAF (unused) ===============================================================================
"unused"    OLAFInputFileName
======  Beddoes-Leishman Unsteady Airfoil Aerodynamics Options  =====================================
4           UAMod
True        FLookup
======  Airfoil Information =========================================================================
1           AFTabMod
1           InCol_Alfa
2           InCol_Cl
3           InCol_Cd
4           InCol_Cm
0           InCol_Cpmin
1           NumAFfiles
"{airfoil_rel}"   AFNames
======  Rotor/Blade Properties  =====================================================================
False       UseBlCm
{blade_lines}
======  Hub Properties ==============================================================================
0.0     VolHub                   - Hub volume (m^3)
0.0     HubCenBx                 - Hub centre of buoyancy x offset (m)
======  Nacelle Properties ==========================================================================
0.0     VolNac                   - Nacelle volume (m^3)
0,0,0   NacCenB                  - Nacelle CoB position (m)
======  Tail fin Aerodynamics =======================================================================
False         TFinAero           - Calculate tail fin aerodynamics (flag)
"unused"      TFinFile           - Tail fin input file
======  Tower Influence and Aerodynamics ============================================================
0                      NumTwrNds   - Number of tower nodes
TwrElev                TwrDiam                TwrCd                  TwrTI  TwrCb
(m)                    (m)                    (-)                    (-)    (-)
======  Outputs =====================================================================================
True                   SumPrint    - Print summary file
0                      NBlOuts     - Number of blade-node output channels
1, 2, 3                BlOutNd     - Blade nodes to output (-)
0                      NTwOuts     - Number of tower-node output channels
1, 2, 3                TwOutNd     - Tower nodes to output (-)
                       OutList     - Channel names follow, terminated by END
"RtAeroCp"
"RtAeroCq"
"RtAeroCt"
"RtAeroFxh"
"RtAeroMxh"
"RtAeroPwr"
"RtSpeed"
"RtTSR"
"RtVAvgxh"
END of input file (the word "END" must appear in the first 3 columns of this last OutList line)
====== Outputs for all blade stations (same ending as above for B1N1.... =========================== [optional section]
0                      BldNd_BladesOut
"All"                  BldNd_BlOutNd
                       OutListAD
END
---------------------------------------------------------------------------------------
"""
    path.write_text(body)


def write_driver(
    path: Path, *, n_blades: int, r_hub: float, r_tip: float,
    precone_deg: float, omega_rpm: float, pitch_deg: float, wind_ms: float,
    tmax_s: float, dt_s: float, air: dict, aero_rel: str,
) -> None:
    """Write the AeroDyn driver primary .dvr file.

    AnalysisType=1 (multiple turbines, one simulation) with NumTurbines=1
    is the simplest path that lets us prescribe constant Omega and pitch.
    AnalysisType=3 would let us combine cases in one process invocation
    but adds parsing complexity; spin up one .dvr per operating point for
    now and revisit if perf becomes a problem.
    """
    rho   = air.get("rho", 1.225)
    mu    = air.get("mu", 1.81206e-5)
    csnd  = air.get("a", 335.0)
    blade_pitch_lines = "\n".join(
        f"{pitch_deg}    BldPitch(1_{i+1})" for i in range(n_blades)
    )
    blade_origin_lines = "\n".join(
        f"0,0,0    BldOrigin_h(1_{i+1})" for i in range(n_blades)
    )
    blade_orient_lines = "\n".join(
        f"{i * 360.0 / n_blades},{-precone_deg},0    BldOrientation_h(1_{i+1})"
        for i in range(n_blades)
    )
    blade_hubrad_lines = "\n".join(
        f"{r_hub}    BldHubRad_bl(1_{i+1})" for i in range(n_blades)
    )
    blade_motion_files = "\n".join(
        f'"unused"  BldMotionFileName(1_{i+1})' for i in range(n_blades)
    )

    body = f"""----- AeroDyn Driver Input File ---------------------------------------------------------
Generated by verification/openfast_docker/run.py
----- Input Configuration ---------------------------------------------------------------
False       Echo
0           MHK
1           AnalysisType
{tmax_s}    TMax
{dt_s}      DT
"{aero_rel}"  AeroFile
----- Environmental Conditions ----------------------------------------------------------
{rho}       FldDens
{mu}        KinVisc
{csnd}      SpdSound
103500.0    Patm
1700.0      Pvap
0           WtrDpth
----- Inflow Data -----------------------------------------------------------------------
0           CompInflow
"unused"    InflowFile
{wind_ms}   HWindSpeed
{max(r_tip * 2.0, 10.0)}    RefHt
0           PLExp
----- Turbine Data ----------------------------------------------------------------------
1           NumTurbines
----- Turbine(1) ------------------------------------------------------------------------
False       BasicHAWTFormat(1)
0,0,0       BaseOriginInit(1)
0,0,0       BaseOrientationInit(1)
False       HasTower(1)
True        HAWTprojection(1)
0,0,0       TwrOrigin_t(1)
0,0,{max(r_tip * 2.0, 10.0)}    NacOrigin_t(1)
0,0,0       HubOrigin_n(1)
0,0,0       HubOrientation_n(1)
----- Turbine(1) Blades -----------------------------------------------------------------
{n_blades}   NumBlades(1)
{blade_origin_lines}
{blade_orient_lines}
{blade_hubrad_lines}
----- Turbine(1) Motion [used only when AnalysisType=1] ---------------------------------
0           BaseMotionType(1)
1           DegreeOfFreedom(1)
0.0         Amplitude(1)
0.0         Frequency(1)
"unused"    BaseMotionFileName(1)
0           NacMotionType(1)
0           NacYaw(1)
"unused"    NacMotionFileName(1)
0           RotMotionType(1)
{omega_rpm}    RotSpeed(1)
"unused"    RotMotionFileName(1)
0           BldMotionType(1)
{blade_pitch_lines}
{blade_motion_files}
----- Time-dependent Analysis -----------------------------------------------------------
"unused"    TimeAnalysisFileName
----- Combined-Case Analysis ------------------------------------------------------------
0           NumCases
HWndSpeed   PLExp        RotSpd       Pitch        Yaw     dT      Tmax  DOF  Amplitude Frequency
(m/s)       (-)          (rpm)        (deg)        (deg)   (s)     (s)    (-)  (m or rad) (Hz)
----- Output Settings -------------------------------------------------------------------
"ES15.8E2"  OutFmt
1           OutFileFmt
0           WrVTK
1           WrVTK_Type
2           VTKHubRad
-1,-1,-1,2,2,2  VTKNacDim
"""
    path.write_text(body)


# ---------------------------------------------------------------------------
# Output parsing
# ---------------------------------------------------------------------------


def parse_out_text(path: Path) -> tuple[list[str], np.ndarray]:
    """Parse a text-format AeroDyn .out file.

    Returns (column_names, data) where data is shape (n_steps, n_cols).
    The file starts with several header lines, then a blank/dashes line,
    then a row of channel names, then a row of units, then the data.
    """
    lines = path.read_text().splitlines()
    # Find the channel header row (the one starting with "Time").
    for i, line in enumerate(lines):
        if line.strip().startswith("Time") and "(" not in line:
            header_idx = i
            break
    else:
        raise RuntimeError(f"Could not find header row in {path}")
    cols = lines[header_idx].split()
    # units line is header_idx + 1, data starts at header_idx + 2.
    data_lines = lines[header_idx + 2:]
    rows = []
    for ln in data_lines:
        s = ln.strip()
        if not s:
            continue
        rows.append([float(x) for x in s.split()])
    if not rows:
        raise RuntimeError(f"No data rows in {path}")
    return cols, np.array(rows)


def average_last_revolution(
    cols: list[str], data: np.ndarray, omega_rpm: float, settle_s: float,
) -> dict[str, float]:
    """Average channels over the last full revolution after `settle_s`."""
    time_idx = cols.index("Time")
    t = data[:, time_idx]
    t_settled = t >= settle_s
    if not t_settled.any():
        raise RuntimeError(
            f"All samples are within settling window ({settle_s} s); "
            f"max t = {t.max():.3f} s"
        )
    # One rotor revolution
    rev_period = 60.0 / max(omega_rpm, 1.0e-6)
    t_avg_start = max(t.max() - rev_period, t[t_settled].min())
    mask = t >= t_avg_start
    avg = {}
    for i, name in enumerate(cols):
        if name == "Time":
            continue
        avg[name] = float(data[mask, i].mean())
    return avg


# ---------------------------------------------------------------------------
# Per-case driver
# ---------------------------------------------------------------------------


def run_case(
    cfg: dict, op: dict, workdir: Path, case_idx: int,
) -> dict[str, float]:
    """Generate inputs, run aerodyn_driver, parse output for one OP."""
    n_blades = int(cfg["rotor"]["n_blades"])
    r_hub    = float(cfg["rotor"]["R_hub_m"])
    r_tip    = float(cfg["rotor"]["R_tip_m"])
    precone  = float(cfg["rotor"].get("precone_deg", 0.0))
    air      = cfg.get("air", {})
    wake     = cfg.get("wake", {})
    omega    = float(op["Omega_rpm"])
    pitch    = float(op["pitch_deg"])
    wind     = float(op["U_wind_ms"])
    settle   = float(op.get("settle_s", 5.0))
    # Time step: 72 azimuth steps per revolution (5 deg resolution) is
    # plenty for steady-state extraction. The image is built single-
    # precision (sqrt(eps) ~= 3.5e-4) and DBEMT_Init refuses to start
    # with dt below sqrt(eps); rev_period/72 = 1/(72*rpm/60) is well
    # above that for any sensible rotor speed.
    rev_period = 60.0 / max(omega, 1.0e-6)
    dt_s = max(rev_period / 72.0, 1.0e-3)
    # Total run time: settle + one extra revolution for averaging.
    tmax = settle + rev_period * 2.0

    case_dir = workdir / f"case_{case_idx:03d}"
    case_dir.mkdir(parents=True, exist_ok=True)

    airfoil_path = case_dir / "airfoil.dat"
    blade_path   = case_dir / "blade.dat"
    aero_path    = case_dir / "aerodyn.dat"
    dvr_path     = case_dir / "driver.dvr"

    write_airfoil(airfoil_path, cfg["airfoil_polar"])
    write_blade(blade_path, cfg["blade_stations"])
    write_aerodyn_primary(
        aero_path, wake, air,
        airfoil_rel=airfoil_path.name,
        blade_rel=blade_path.name,
        dt_s=dt_s,
    )
    write_driver(
        dvr_path, n_blades=n_blades, r_hub=r_hub, r_tip=r_tip,
        precone_deg=precone, omega_rpm=omega, pitch_deg=pitch,
        wind_ms=wind, tmax_s=tmax, dt_s=dt_s, air=air,
        aero_rel=aero_path.name,
    )

    # Invoke aerodyn_driver. Run in the case directory so relative
    # paths in the .dvr resolve correctly.
    proc = subprocess.run(
        [AD_DRIVER, dvr_path.name],
        cwd=case_dir,
        capture_output=True,
        text=True,
        timeout=300,
    )
    if proc.returncode != 0:
        sys.stderr.write(proc.stdout)
        sys.stderr.write(proc.stderr)
        raise RuntimeError(
            f"aerodyn_driver exited with code {proc.returncode} for case {case_idx}"
        )

    # Output file is <dvr_stem>.T1.out
    out_path = case_dir / f"{dvr_path.stem}.T1.out"
    if not out_path.exists():
        # Try other common locations
        cands = list(case_dir.glob("*.out"))
        if cands:
            out_path = cands[0]
        else:
            raise RuntimeError(
                f"aerodyn_driver did not produce a .out file in {case_dir}"
            )

    cols, data = parse_out_text(out_path)
    avg = average_last_revolution(cols, data, omega, settle)
    avg["case"] = case_idx
    avg["U_wind_ms"] = wind
    avg["Omega_rpm"] = omega
    avg["pitch_deg"] = pitch
    return avg


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--config", required=True)
    ap.add_argument("--output-dir", default="/out")
    ap.add_argument("--workdir", default=None,
                    help="Where to drop the per-case AeroDyn inputs/outputs. "
                         "Defaults to a tempdir; pass for debug.")
    args = ap.parse_args()

    cfg = yaml.safe_load(Path(args.config).read_text())
    out_dir = Path(args.output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    name = cfg["name"]

    if args.workdir:
        workdir = Path(args.workdir)
        workdir.mkdir(parents=True, exist_ok=True)
        keep_workdir = True
    else:
        workdir = Path(tempfile.mkdtemp(prefix="aerodyn_driver_"))
        keep_workdir = False

    print(f"Workdir: {workdir}")
    print(f"Cases: {len(cfg['operating_points'])}")

    rows = []
    try:
        for i, op in enumerate(cfg["operating_points"]):
            print(f"  [{i+1}/{len(cfg['operating_points'])}] "
                  f"U={op['U_wind_ms']} Omega={op['Omega_rpm']} pitch={op['pitch_deg']}",
                  flush=True)
            row = run_case(cfg, op, workdir, i)
            rows.append(row)
    finally:
        if not keep_workdir:
            shutil.rmtree(workdir, ignore_errors=True)

    # Write CSV
    out_path = out_dir / f"{name}_openfast.csv"
    if rows:
        cols = sorted({k for r in rows for k in r.keys()})
        # Sort so case/op columns come first
        head = ["case", "U_wind_ms", "Omega_rpm", "pitch_deg"]
        cols = head + [c for c in cols if c not in head]
        with out_path.open("w", newline="") as fh:
            w = csv.DictWriter(fh, fieldnames=cols)
            w.writeheader()
            w.writerows(rows)
        print(f"Wrote {out_path}")
    else:
        print("No rows produced.")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
